# Generated by Django 2.1.3 on 2018-12-10 13:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Common_User_Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feedback', models.CharField(max_length=300)),
                ('UploadTime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Filename', models.CharField(max_length=60)),
                ('Description', models.CharField(default='Description', max_length=300)),
                ('UploadTime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Status', models.CharField(max_length=30)),
                ('StartDate', models.DateTimeField(verbose_name='Start Date')),
                ('DueDate', models.DateTimeField(verbose_name='Due Date')),
                ('Done', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=60)),
                ('Description', models.CharField(default='Description', max_length=300)),
                ('StartDate', models.DateTimeField(verbose_name='Start Date')),
                ('DueDate', models.DateTimeField(verbose_name='Due Date')),
                ('Done', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='QA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=300)),
                ('Answer', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Description', models.CharField(default='Description', max_length=300)),
                ('Status', models.CharField(max_length=30)),
                ('Priority', models.CharField(max_length=30)),
                ('StartDate', models.DateTimeField(verbose_name='Start Date')),
                ('DueDate', models.DateTimeField(verbose_name='Due Date')),
                ('Done', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=60)),
                ('Fullname', models.CharField(max_length=60)),
                ('DOB', models.DateTimeField(verbose_name='Day Of Birth')),
                ('Gender', models.CharField(max_length=10)),
                ('Company', models.CharField(max_length=30)),
                ('Role', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='Assignee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectManagement.User'),
        ),
        migrations.AddField(
            model_name='task',
            name='Project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectManagement.Project'),
        ),
        migrations.AddField(
            model_name='qa',
            name='Task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectManagement.Task'),
        ),
        migrations.AddField(
            model_name='qa',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectManagement.User'),
        ),
        migrations.AddField(
            model_name='phase',
            name='Task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectManagement.Task'),
        ),
        migrations.AddField(
            model_name='file',
            name='Task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectManagement.Task'),
        ),
        migrations.AddField(
            model_name='file',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectManagement.User'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='Filename',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectManagement.File'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='Project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectManagement.Project'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectManagement.User'),
        ),
        migrations.AddField(
            model_name='common_user_task',
            name='Task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectManagement.Task'),
        ),
        migrations.AddField(
            model_name='common_user_task',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectManagement.User'),
        ),
    ]
