# Generated by Django 2.1.3 on 2018-12-14 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='DueDate',
            field=models.DateField(verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='StartDate',
            field=models.DateField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='DueDate',
            field=models.DateField(verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='StartDate',
            field=models.DateField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='DueDate',
            field=models.DateField(verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='StartDate',
            field=models.DateField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='DOB',
            field=models.DateField(verbose_name='Day Of Birth'),
        ),
    ]
