# Generated by Django 2.1.3 on 2018-12-17 02:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManagement', '0002_auto_20181214_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='UploadTime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='file',
            name='UploadTime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
