# Generated by Django 2.1.3 on 2018-12-21 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManagement', '0003_auto_20181217_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ProjectManagement.User'),
        ),
    ]
