# Generated by Django 2.1.3 on 2018-12-24 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManagement', '0005_common_user_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Url',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
