# Generated by Django 2.2 on 2019-05-05 07:53

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import information.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('role', models.CharField(max_length=50)),
                ('profile_pic', models.FileField(blank=True, max_length=1000, null=True, upload_to=information.models.img_url)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('secretary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secretary', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=50, verbose_name='Thứ')),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_belong', to='information.Class')),
                ('lesson', models.ManyToManyField(related_name='lesson', to='information.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField(default=datetime.date.today)),
                ('isHeadTeacher', models.BooleanField(default=True)),
                ('degree', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('class_list', models.ManyToManyField(related_name='teachers', to='information.Class')),
                ('subjects', models.ManyToManyField(related_name='teachers', to='information.Subject')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField(default=datetime.date.today)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='information.Class')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='MarkSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(default=datetime.date.today)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('mark_type', models.CharField(choices=[('Kiểm tra giữa kì', 'Kiểm tra giữa kì'), ('Kiểm tra cuối kì', 'Kiểm tra cuối kì'), ('Kiển tra một tiết', 'Kiểm tra một tiết'), ('Kiểm tra 15 phút', 'Kiểm tra 15 phút'), ('Kiểm tra 45 phút', 'Kiểm tra 45 phút'), ('Kiểm tra miệng', 'Kiểm tra miệng'), ('Kiểm tra vở', 'Kiểm tra vở'), ('Kiểm tra chất lượng đầu năm', 'Kiểm tra chất lượng đầu năm')], max_length=40, verbose_name='Loại điểm')),
                ('multi', models.SmallIntegerField(default=1)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.Student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Check_in',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.Student')),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(default=datetime.date.today)),
                ('reason', models.CharField(default='Phụ huynh chưa điền thông tin nghỉ phép', max_length=200)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.Student')),
            ],
        ),
    ]
