# Generated by Django 2.1.5 on 2019-05-18 03:16

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import information.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('role', models.CharField(max_length=50)),
                ('profile_pic', models.FileField(blank=True, max_length=1000, null=True, upload_to=information.models.img_url)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(default=datetime.date.today)),
                ('reason', models.CharField(default='Phụ huynh chưa điền thông tin nghỉ phép', max_length=200)),
                ('approved_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('isNotified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Check_in',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('isNotified', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('study_time', models.CharField(default='2019-2022', max_length=11)),
                ('secretary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secretary', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='MarkSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(default=datetime.date.today)),
                ('score', models.FloatField(default=0)),
                ('mark_type', models.CharField(choices=[('Kiểm tra giữa kì', 'Kiểm tra giữa kì'), ('Kiểm tra cuối kì', 'Kiểm tra cuối kì'), ('Kiển tra một tiết', 'Kiểm tra một tiết'), ('Kiểm tra 15 phút', 'Kiểm tra 15 phút'), ('Kiểm tra 45 phút', 'Kiểm tra 45 phút'), ('Kiểm tra miệng', 'Kiểm tra miệng'), ('Kiểm tra vở', 'Kiểm tra vở'), ('Kiểm tra chất lượng đầu năm', 'Kiểm tra chất lượng đầu năm')], max_length=40, verbose_name='Loại điểm')),
                ('multi', models.PositiveSmallIntegerField(default=1)),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('isNotified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.CharField(default='', max_length=300)),
                ('is_seen', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField(default=datetime.date.today)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='information.Class')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Sinh học', 'Sinh học'), ('Toán học', 'Toán học'), ('Lịch sử', 'Lịch sử'), ('Địa lý', 'Địa lý'), ('Vật lý', 'Vật lý'), ('Hóa học', 'Hóa học'), ('Văn học', 'Văn học'), ('Ngoại ngữ', 'Ngoại ngữ'), ('Giáo dục thể chất', 'Giáo dục thể chất'), ('Giáo dục công dân', 'Giáo dục công dân'), ('Âm nhạc', 'Âm nhạc'), ('Mỹ thuật', 'Mỹ thuật'), ('Công nghệ', 'Công nghệ'), ('Tin học', 'Tin học'), ('Nghỉ học', 'Nghỉ học')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField(default=datetime.date.today)),
                ('isHeadTeacher', models.BooleanField(default=True)),
                ('degree', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('class_list', models.ManyToManyField(related_name='teachers', to='information.Class')),
                ('subjects', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='information.Subject')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=50, verbose_name='Thứ')),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_belong', to='information.Class')),
                ('lesson1', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='lesson1', to='information.Subject')),
                ('lesson2', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='lesson2', to='information.Subject')),
                ('lesson3', models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, related_name='lesson3', to='information.Subject')),
                ('lesson4', models.ForeignKey(default='3', on_delete=django.db.models.deletion.CASCADE, related_name='lesson4', to='information.Subject')),
                ('lesson5', models.ForeignKey(default='4', on_delete=django.db.models.deletion.CASCADE, related_name='lesson5', to='information.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.Student'),
        ),
        migrations.AddField(
            model_name='marksheet',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.Student'),
        ),
        migrations.AddField(
            model_name='marksheet',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.Subject'),
        ),
        migrations.AddField(
            model_name='check_in',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.Student'),
        ),
        migrations.AddField(
            model_name='absence',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.Student'),
        ),
    ]
