# Generated by Django 2.1.5 on 2019-05-20 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='isAgree',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='absence',
            name='isApproved',
            field=models.BooleanField(default=False),
        ),
    ]
