# Generated by Django 2.2 on 2019-05-13 03:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='lesson',
        ),
        migrations.AddField(
            model_name='timetable',
            name='lesson1',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='lesson1', to='information.Subject'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='lesson2',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='lesson2', to='information.Subject'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='lesson3',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, related_name='lesson3', to='information.Subject'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='lesson4',
            field=models.ForeignKey(default='3', on_delete=django.db.models.deletion.CASCADE, related_name='lesson4', to='information.Subject'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='lesson5',
            field=models.ForeignKey(default='4', on_delete=django.db.models.deletion.CASCADE, related_name='lesson5', to='information.Subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(choices=[('Sinh học', 'Sinh học'), ('Toán học', 'Toán học'), ('Lịch sử', 'Lịch sử'), ('Địa lý', 'Địa lý'), ('Vật lý', 'Vật lý'), ('Hóa học', 'Hóa học'), ('Văn học', 'Văn học'), ('Ngoại ngữ', 'Ngoại ngữ'), ('Giáo dục thể chất', 'Giáo dục thể chất'), ('Giáo dục công dân', 'Giáo dục công dân'), ('Âm nhạc', 'Âm nhạc'), ('Mỹ thuật', 'Mỹ thuật'), ('Công nghệ', 'Công nghệ'), ('Nghỉ học', 'Nghỉ học')], max_length=100),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.CharField(default='Liên hệ giáo viên Vũ Lê Hoàng tại địa chỉ email hoangvlbk61@gmail.com', max_length=300)),
                ('is_seen', models.BooleanField(default=False)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.Student')),
            ],
        ),
    ]
