# Generated by Django 2.2 on 2019-05-14 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_auto_20190513_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='study_time',
            field=models.CharField(default='2019-2022', max_length=11),
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='multi',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subjects',
        ),
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='information.Subject'),
        ),
    ]
