# Generated by Django 2.2 on 2019-05-14 08:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_auto_20190514_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='approved_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 8, 20, 18, 643119, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='check_in',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 8, 20, 18, 637616, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='marksheet',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 8, 20, 18, 645621, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(choices=[('Sinh học', 'Sinh học'), ('Toán học', 'Toán học'), ('Lịch sử', 'Lịch sử'), ('Địa lý', 'Địa lý'), ('Vật lý', 'Vật lý'), ('Hóa học', 'Hóa học'), ('Văn học', 'Văn học'), ('Ngoại ngữ', 'Ngoại ngữ'), ('Giáo dục thể chất', 'Giáo dục thể chất'), ('Giáo dục công dân', 'Giáo dục công dân'), ('Âm nhạc', 'Âm nhạc'), ('Mỹ thuật', 'Mỹ thuật'), ('Công nghệ', 'Công nghệ'), ('Tin học', 'Tin học'), ('Nghỉ học', 'Nghỉ học')], max_length=100),
        ),
    ]
