# Generated by Django 2.2 on 2019-05-14 08:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0004_auto_20190514_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='approved_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='check_in',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
