# Generated by Django 2.2 on 2019-05-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0005_auto_20190514_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='isNotified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='check_in',
            name='isNotified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marksheet',
            name='isNotified',
            field=models.BooleanField(default=False),
        ),
    ]
